
methodType form 
methodCode melo 
seed 0 
mipmaxtime 500
outputFlagGrbMIP 1
outputFlagGrbMSLP 0
maxnodes -2 
typeUserCut 0 
# typeUserCut 3 
mipPresolve -1
# mipPresolve 0
# mipPresolve 1
# mipPresolve 2
printsol 1

# warm-start
mslpa 15 
mslpr M 