# Example of a configuration file for MSLP
# Format: <parameter_name> <value>
# You can comment the parameters by using the '#' symbol at the beginning of the line
# Duplicate the file with a new name and modify the parameters as needed

method_type heur 
method_code mslp
seed 24
greedy_service_order random 
alpha 0.01
threads 1
output_flag_grb_MSLP 0
mslpa 60
mslpr M
max_time 600
output ./logs/
print_sol 0
solver_method A

