method_type form
method_code mip_grb
seed 0
mip_grb_max_time 600
output_flag_grb_mip 1
max_nodes -2
mip_grb_presolve -1

mip_grb_heuristics 0
print_sol 1

# Add which constraints should be active. The range (1-29) is mandatory for this problem. No space between characters
# Valid inequalities from 35-46
constraints_used_mip_str 1-29,35-46
