method_type form
method_code melo
seed 0
mip_max_time 600
# mip_max_time 0
output_flag_grb_mip 1
output_flag_grb_mslp 0
max_nodes -1
type_user_cut 0
# type_user_cut 3
mip_presolve -1
# mip_presolve 0
# mip_presolve 1
# mip_presolve 2

mip_heuristics 0

print_sol 1

threads 8

# Add which constraints should be active. The range (1-29) is mandatory for this problem
constraints_used_melo_mip_str 1-29,43

