method_type form
method_code barlogon_hx
seed 0
mip_max_time 100
hx_max_time 10
output_flag_grb_mip 1
output_flag_grb_mslp 0
max_nodes -2
type_user_cut 0
# type_user_cut 3
mip_presolve -1
# mip_presolve 0
# mip_presolve 1
# mip_presolve 2
print_sol 1

# warm-start
mslp_a 15
mslp_r M
validate_synchronization False
# validate_synchronization True
