
method_type heur 
method_code lmns 
seed 34 # RNG seed



outputFlagGrbMIP 0
outputFlagGrbLMNS 1
output_flag_grb_MSLP 0

###### Initial solution ######
# mslpr F # first feasible solution

mslpr M # time limit
mslpa 30

# mslpr I # iterações
# mslpa 60000

greedy_service_order random 
alpha 0.10 

#### Stop criteria LMNS ####
lmnsr M
# lmnsa 1500
lmnsa 600
# lmnsa 400
# lmnsa 300
# lmnsa 10

# Too small
# lmnsRepairTime 5
# lmnsRepairTime 10
# lmnsRepairTime 15
# lmnsRepairTime 20
# lmnsRepairTime 30


lmnsRepairTime 50
# lmnsRepairTime 100


lmnsMIPFocus 0 # default: balance btwn finding new feas sols & proving that the curr sol is optimal
# lmnsMIPFocus 1 # finding feasible solutions quickly
# lmnsMIPFocus 2 # proving optimality
# lmnsMIPFocus 3 # objective bound is moving very slowly (or not at all)

lmnsGapToBiggerDestruction 5
lmnsGapToSmallerDestruction 95

lmnsWeightShawDistProx 1
lmnsWeightShawEarlProx 1
lmnsWeightShawSameRoute 1
lmnsWeightShawDemandSim 1

lmnsReqRApplyMIPStart true
# lmnsReqRApplyMIPStart false

lmnsAcceptanceCriteria H # hill climbing
# lmnsAcceptanceCriteria M # metropolis
# lmnsAcceptanceCriteria S # simulated annealing

lmnsMetropolisTemp 100

lmnsSimulatedAnnealingTemp 100
lmnsSimulatedAnnealingCool 0.95

mipPresolve -1

output ./logs/
printsol 1