method_type form
method_code melo
seed 0
mip_max_time 600
# mip_max_time 0
output_flag_grb_mip 1
output_flag_grb_mslp 0
max_nodes -2
type_user_cut 0
# type_user_cut 3
mip_presolve -1
# mip_presolve 0
# mip_presolve 1
# mip_presolve 2

mip_heuristics 0
print_sol 1

# warm-start
mslp_a 15
mslp_r M

# Add which constraints should be active. The range (1-29) is mandatory for this problem
# constraints_used_mip_str 1-29,35-38
constraints_used_mip_str 1-29,35-46
# constraints_used_mip_str 1-29,35-43,46
# constraints_used_mip_str 1-29,36-37,39-40,42-45
# constraints_used_mip_str 1-29,35,41-46
# constraints_used_mip_str 1-29,41-46
