method_type form
method_code mip_hx
seed 0
hx_max_time 600
output_flag_grb_mip 1
output_flag_grb_mslp 0
max_nodes -2
type_user_cut 0
# type_user_cut 3
mip_presolve -1
# mip_presolve 0
# mip_presolve 1
# mip_presolve 2
print_sol 1

# warm-start
mslp_a 15
mslp_r M

# constraints_used_mip_str 1-29
constraints_used_mip_str 1-8,13-29

