
methodType heur 
methodCode mslp 
seed 0 
threads 1
greedy_service_order random 
outputFlagGrbMSLP 0
mslpa 60000
mslpr I
maxtime 3600
output ./logs/
printsol 1
solverMethod A
alpha 0.05 # selected from preliminary experiments